/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package swing;

import java.util.HashMap;

/**
 *
 * @author seruj
 */
public class PanelStatus extends javax.swing.JLayeredPane {

    private final HashMap<Integer,PanelStatus_Item>list = new HashMap<>();  
    
    
    public PanelStatus() {
        initComponents();
    }
    
    public void addItem (int fileID,String fileName,String fileSize){
        PanelStatus_Item item = new PanelStatus_Item();
        item.setFile(fileName, fileSize);
        list.put(fileID, item);
        this.add(item);
        this.repaint();
        this.revalidate();
    }
    
    public void updateStatus (int fileID, int values){
       list.get(fileID).showStatus(values);
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panelStatus_item2 = new swing.PanelStatus_Item();

        setOpaque(false);
        setLayout(new javax.swing.BoxLayout(this, javax.swing.BoxLayout.Y_AXIS));
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private swing.PanelStatus_Item panelStatus_item2;
    // End of variables declaration//GEN-END:variables
}
